[package]
name = "rust-effects"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
async-executor = "1.5.1"
async-oneshot = "0.5.0"
async-trait = "0.1.73"
futures = "0.3.28"
